app_ppw/urls.py
from django.urls import path
from . import views

app_name = 'app_ppw'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('story1', views.story1, name='story1'),

    path('add_kuliah', views.add_kuliah, name='add_kuliah'),
    path('list_kuliah/', views.list_kuliah, name='list_kuliah'),
    path('detail_kuliah/<str:id>', views.detail_kuliah, name='detail_kuliah'),
    path('delete_kuliah/<str:id>', views.delete_kuliah, name='delete_kuliah'),
    path('list_kuliah/<str:id>', views.delete_kuliah_confirm, name='delete_kuliah_confirm'),

    path('jadwal_kegiatan/', views.list_event, name='jadwal_kegiatan'),
    path('tambah_kegiatan/', views.add_event, name='tambah_kegiatan'),
    path('tambah_peserta/<str:id>/', views.add_member, name='tambah_peserta'),
]

project_ppw/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from story8.views import search_books
from story9.views import login, logout, register, welcome
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_ppw.urls')),
    path('books/', include('story8.urls')),
    path('data/', search_books),

    path('login/', login, name='login'),
    path('logout/$', logout, name='logout'),
    path('register/', register, name='register'),
    path('welcome/', welcome, name='welcome'),

]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.books, name='books'),
]

app_ppw/models.py
from django.db import models

# Create your models here.

jadwal_kegiatan/models.py
from django.db import models

# Create your models here.
class JadwalKegiatan(models.Model):
    nama_Kegiatan = models.CharField(max_length=100, null=True)

class Peserta(models.Model):
    nama_Peserta = models.CharField(max_length=100, null=True)
    kegiatan = models.ForeignKey(to=JadwalKegiatan, on_delete = models.CASCADE, null=True)

jadwal_kuliah/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator 

# Create your models here.
class MataKuliah(models.Model):
    nama_Mata_Kuliah = models.CharField(max_length=100, null=True)
    dosen_Pengajar = models.CharField(max_length=100, null=True)
    SKS = models.IntegerField(null=True, validators=[MinValueValidator(1), MaxValueValidator(10)])
    deskripsi = models.CharField(max_length=700, null=True)
    SEMESTER = (
        ('Gasal', 'Gasal'),
        ('Genap', 'Genap'),
    )
    semester = models.CharField(max_length=5, choices=SEMESTER, null=True)
    tahun_Ajaran = models.CharField(max_length=10, null=True)
    ruang_Kelas = models.CharField(max_length=10, null=True)

    # Auto capitalize for every word of nama mata kuliah and dosen pengajar
    def save(self, *args, **kwargs):
        fields = ['nama_Mata_Kuliah', 'dosen_Pengajar']
        for field_name in fields:
            val = getattr(self, field_name, False)
            if val:
                split_val = val.split(" ")
                for i in range(len(split_val)):
                    split_val[i] = split_val[i].capitalize()
                
                new_val = " ".join(split_val)
                setattr(self, field_name, new_val)

        super(MataKuliah, self).save(*args, **kwargs)

jadwal_kegiatan/forms.py
from django import forms
from .models import JadwalKegiatan, Peserta

class Input_Kegiatan(forms.ModelForm):
    class Meta:
        model = JadwalKegiatan
        fields = [
            'nama_Kegiatan',  
        ]
        widgets = {
            'nama_Kegiatan' : forms.TextInput(attrs={'class':'form-style mb-5'}),
        }

class Input_Peserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = [
            'nama_Peserta',  
        ]
        widgets = {
            'nama_Peserta' : forms.TextInput(attrs={'class':'form-style mb-5'}),
        }

jadwal_kuliah/forms.py
from django import forms
from .models import MataKuliah

class Input_Form(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'nama_Mata_Kuliah', 
            'dosen_Pengajar', 
            'SKS', 
            'deskripsi', 
            'semester', 
            'tahun_Ajaran',
            'ruang_Kelas',
        ]
        widgets = {
            'nama_Mata_Kuliah' : forms.TextInput(attrs={'class':'form-style mb-5'}),
            'dosen_Pengajar' : forms.TextInput(attrs={'class':'form-style mb-5'}),
            'SKS': forms.NumberInput(
                    attrs={
                        'class':'form-style mb-5',
                        'placeholder': 'Range 1-10'
                    }),
            'deskripsi' : forms.Textarea(
                            attrs={
                                'class':'form-style mb-5', 
                                'id':'deskripsi',
                                'rows': 10,
                                'cols': 50,
                                'placeholder': 'Deskripsi mengenai mata kuliah',
                            }),
            'semester' : forms.Select(attrs={'class':'form-style mb-5', 'id':'semester'}),
            'tahun_Ajaran' : forms.TextInput(attrs={'class':'form-style mb-5'}),
            'ruang_Kelas' : forms.TextInput(attrs={'class':'form-style mb-5'}),
        }

app_ppw/views.py
from django.shortcuts import render, redirect
from jadwal_kuliah.forms import Input_Form
from jadwal_kuliah.models import MataKuliah
from jadwal_kegiatan.models import JadwalKegiatan, Peserta
from jadwal_kegiatan.forms import Input_Kegiatan, Input_Peserta

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def story1(request):
    return render(request, 'story1.html')

# Fitur List Kuliah
def add_kuliah(request):
    form = Input_Form(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('app_ppw:list_kuliah')
    else:
        form=Input_Form()
    
    response = {
        'form' : form
    }

    return render(request, 'jadwal_kuliah.html', response)

def list_kuliah(request):
    mata_kuliah = MataKuliah.objects.all()
    response = {
        'mata_kuliah' : mata_kuliah
    }

    return render(request, 'list_kuliah.html', response)

def detail_kuliah(request, id):
    response = {
        'kuliah' : MataKuliah.objects.get(pk=id)
    }
    return render(request, 'detail_kuliah.html', response)

def delete_kuliah(request, id):
    response = {
        'kuliah' : MataKuliah.objects.get(pk=id)
    }
    return render(request, 'delete_kuliah.html', response)

def delete_kuliah_confirm(request, id):
    MataKuliah.objects.get(pk=id).delete()
    mata_kuliah = MataKuliah.objects.all()
    response = {
        'mata_kuliah' : mata_kuliah
    }

    return render(request, 'list_kuliah.html', response)

# Fitur List Event
def list_event(request):
    kegiatan = JadwalKegiatan.objects.all()
    member = Peserta.objects.all()
    response = {
        'list_kegiatan' : kegiatan,
        'list_member' : member,
    }

    return render(request, 'jadwal_kegiatan.html', response)

def add_event(request):
    form = Input_Kegiatan(request.POST or None) 
    if form.is_valid():
        form.save()
        form = Input_Kegiatan()
        
    else:
        form=Input_Kegiatan()
    
    response = {
        'form' : form
    }

    return render(request, 'tambah_kegiatan.html', response)

def add_member(request, id):
    form = Input_Peserta(request.POST or None) 
    if form.is_valid():
        form.save()
        saved_peserta = Peserta.objects.all().last()
        saved_peserta.kegiatan = JadwalKegiatan.objects.get(pk=id)
        saved_peserta.save()
        form = Input_Peserta()
    else:
        form = Input_Peserta()
    
    response = {
        'form' : form,
        'id' : id,
    }

    return render(request, 'tambah_peserta.html', response)

jadwal_kegiatan/views.py
from django.shortcuts import render

# Create your views here.

jadwal_kuliah/views.py
from django.shortcuts import render

# Create your views here.

app_ppw/templates/about.html
{% extends 'base.html' %}
{% load static %}  

<head>
	{% block head %}
	<title>About Me</title>
	{% endblock %}
</head>

<body>
	{% block body %}
	<div class="sub-section mb-4 about-section">
		<h1><span class="name-title">About</span> Me</h1>
		<p>Seorang mahasiswa di Fakultas Ilmu Komputer, Universitas Indonesia. Sejak SMA, saya mulai mempelajari dasar-dasar pemrorgraman web seperti HTML dan CSS. Sekarang saya sedang mendalami desain dengan menjadi staf desain di 2 organisasi di Fasilkom UI. Saya senang menggambar dan baca novel, terutama buku-buku Agatha Christie!</p>
	</div>

	<div class="sub-section" id="acc-section">
		<div class="acc-container">
			<div class="accordion">
				<button class="accordion-title">Aktivitas Saat Ini</button>
				<button class="down">V</button>
				<button class="up">^</button>
			</div>
			<div class="panel">
				<p class="accordion-content py-4">Mengerjakan story PPW :)</p>
			</div>
		</div>

		<div class="acc-container">
			<div class="accordion">
				<button class="accordion-title">Pengalaman Organisasi</button>
				<button class="down">V</button>
				<button class="up">^</button>
			</div>
			<div class="panel">
				<p class="accordion-content py-4">Staf Media di DPM dan FUKi</p>
			</div>
		</div>

		<div class="acc-container">
			<div class="accordion">
				<button class="accordion-title">Pengalaman Kepanitiaan</button>
				<button class="down">V</button>
				<button class="up">^</button>
			</div>
			<div class="panel">
				<p class="accordion-content py-4">PJ Kreatif dan Dokumentasi BETIS 2021</p>
			</div>
		</div>

		<div class="acc-container">
			<div class="accordion">
				<button class="accordion-title">Prestasi</button>
				<button class="down">V</button>
				<button class="up">^</button>
			</div>
			<div class="panel">
				<p class="accordion-content py-4">Belum ada nih :(</p>
			</div>
		</div>
	</div>

	<script>
		$(document).ready(function(){
			$(".accordion-title").on("click", function(){
				$(this).parent().next().toggle();
			});

			$(".up").on("click", function(){
				var content = $(this).parent().parent();
				var prev = content.prev();
				prev.before(content.detach());
			});

			$(".down").on("click", function(){
				var content = $(this).parent().parent();
				var next = content.next();
				next.after(content.detach());
			});
		});
		
	</script>


	{% endblock %}

</body>

app_ppw/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @font-face {
            font-family: Gilroy-EB;
            src: url("{% static 'fonts/Gilroy-FREE/Gilroy-ExtraBold.otf' %}");
            }
        @font-face {
            font-family: Gilroy-Light;
            src: url("{% static 'fonts/Gilroy-FREE/Gilroy-Light.otf' %}");
        }
    </style>
    {% block head %}
    <title></title>
    {% endblock %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css'  %}">

    <!-- Local AJAX-->
    <script src="{% static 'jquery-3.5.1.min.js'  %}"></script>

    <!-- jquery -->
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script> -->

</head>

<!-- body -->
<body>
    <nav class="navbar navbar-expand-lg d-flex navbar-dark mx-auto">
        <span class="navbar-brand mb-0 h1"> <a href="{% url 'app_ppw:index' %}">alishayb</a></span>
        <button class="navbar-toggler ml-auto" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav mx-auto mt-3">
                <li class="nav-item mx-4">
                  <a class="nav-link home" href="{% url 'app_ppw:index' %}">HOME</a>
                </li>
                <li class="nav-item mx-4">
                    <a class="nav-link" href="{% url 'app_ppw:about' %}">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Course/Event List
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">    
                        <a class="dropdown-item" href="{% url 'app_ppw:list_kuliah' %}">Course List</a>
                        <a class="dropdown-item" href="{% url 'app_ppw:jadwal_kegiatan' %}">Event List</a>
                    </div>
                </li>
                <li class="nav-item mx-4">
                    <a class="nav-link" href="{% url 'story8:books' %}">Books Search</a>
                </li>
                <li class="nav-item mx-4">
                    <a class="nav-link" href="{% url 'login' %}">Sign Up</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block body %}
    <section>

    </section>
    {% endblock %}
            
    <div class="contact d-flex flex-column" id="contact">
        <h3 class="mb-4 mt-5">Contact me via: </h3>
        <div class="social-media d-flex">
            <p><span class="social mr-5"><i class="fab fa-github"></i><a href="https://github.com/alishayb">  @alishayb </a></span>
            <span class="social mr-5"><i class="fab fa-instagram mr-1"></i><a href="https://www.instagram.com/alishabakri/"> @alishabakri </a></span>
            <span class="social"><i class="fab fa-linkedin mr-1"></i><a href="https://www.linkedin.com/in/alisha-yumna-bakri-922682166/"> Alisha Yumna Bakri</a>
            </p>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
</body>
</html>

app_ppw/templates/delete_kuliah.html
{% extends 'base.html' %}
{% load static %}  

<head>
    {% block head %}
    <title>Delete Course</title>
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="mt-5">
        <h3 class="data-content">Are you sure you want to delete {{ kuliah.nama_Mata_Kuliah }} ?</h3>    
    </div>

    <div class="box-delete-kuliah d-flex flex-row">
        <div class="box-delete rounded mr-4">
            <a href="{% url 'app_ppw:delete_kuliah_confirm' kuliah.id %}">Delete</a>
        </div>
        <div class="box-delete rounded">
            <a href="{% url 'app_ppw:list_kuliah' %}">Cancel</a>
        </div>
    </div>

    {% endblock %}
</body>

app_ppw/templates/detail_kuliah.html
{% extends 'base.html' %}
{% load static %}  

<head>
    {% block head %}
    <title>Course Detail</title>
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="sub-section mb-4">
        <h1><span class="name-title">Course</span> Detail</h1>
    </div>
    <div class="detail-kuliah-content">
        <div class="content">
            <p class="title-content">Nama Mata Kuliah</p>
            <p class="data-content">{{kuliah.nama_Mata_Kuliah}}</p>
        </div>
        <div class="content">
            <p class="title-content">Dosen Pengajar</p>
            <p class="data-content">{{kuliah.dosen_Pengajar}}</p>
        </div>
        <div class="content">
            <p class="title-content">SKS</p>
            <p class="data-content">{{kuliah.SKS}}</p>
        </div>
        <div class="content d-flex flex-column">
            <p class="title-content">Deskripsi</p>
            <p class="data-content deskripsi">{{kuliah.deskripsi}}</p>
        </div>
        <div class="content">
            <p class="title-content">Semester</p>
            <p class="data-content">{{kuliah.semester}}</p>
        </div>
        <div class="content">
            <p class="title-content">Tahun Ajaran</p>
            <p class="data-content">{{kuliah.tahun_Ajaran}}</p>
        </div>
        <div class="content">
            <p class="title-content">Ruang Kelas</p>
            <p class="data-content">{{kuliah.ruang_Kelas}}</p>
        </div>
    </div>
        
    {% endblock %}
</body>

app_ppw/templates/index.html
{% extends 'base.html' %}
{% load static %}   
<head>
    {% block head %}
    <title>Alisha Y.B.</title>
    {% endblock %}

</head>
<body>
    {% block body %}
    <section class="mt-4">
        <div class="desc">
            <h1>Hello! I'm <span class="name-title">Alisha.</span></h1>
            <p>Computer science student, eager to learn new things especially about web development!</p>
        </div>

        <div class="works d-flex flex-column" id="works">
            <h3 class="pb-5">PREVIOUS PROJECT</h3>
            <img class="todo pb-4" src="{% static 'images/todoapp.png' %}"/>
            <p class="todo-desc"> <a href="https://github.com/gpersable/-TODO-SpringBootApp">// TODO</a> is a Spring Boot application that can help to remind you on your deadlines. </p>
            <p class="todo-desc"> Made in a collaboration with <a class="collaborator" href="https://github.com/gpersable">Gita</a>, <a class="collaborator" href="https://github.com/natsyz">Nata</a>, and <a class="collaborator" href="https://github.com/kanzee">Khansa</a>.</p>
        </div>

        <div class="experience d-flex flex-column">
            <h3 class="pb-4">EXPERIENCE</h3>
            <div class="detail-experience">
                <div class="content">
                    <p class="title-content">Feb 2020 - Present</p>
                    <p class="data-content">Media Beureau Staff at FUKI Fasilkom UI</p>
                </div>
                <div class="content">
                    <p class="title-content">Feb 2020 - Present</p>
                    <p class="data-content">Media Division Staff at DPM Fasilkom UI</p>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="bioedu">
                <div class="biodata mb-5" id="profile">
                    <h3 class="pb-4">BIODATA</h3>
                    <div class="detail-biodata d-flex">
                        <div class="biodata-1">
                            <div class="content">
                                <p class="title-content">Full Name</p>
                                <p class="data-content">Alisha Yumna Bakri</p>
                            </div>
                            <div class="content">
                                <p class="title-content">Nickname</p>
                                <p class="data-content">Alisha</p>
                            </div>
                            <div class="content">
                                <p class="title-content">Address</p>
                                <p class="data-content">Depok, Jawa Barat</p>
                            </div>
                        </div>
                        <div class="biodata-2">
                            <div class="content">
                                <p class="title-content">Age</p>
                                <p class="data-content">18</p>
                            </div>
                            <div class="content">
                                <p class="title-content">Gender</p>
                                <p class="data-content">Female</p>
                            </div>
                            <div class="content">
                                <p class="title-content">Hobbies</p>
                                <p class="data-content">Drawing and reading</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="education">
                    <h3 class="pb-4">EDUCATION</h3>
                    <div class="detail-edu">
                        <div class="content">
                            <p class="title-content">2016 - 2019</p>
                            <p class="data-content">SMAN 26 Jakarta</p>
                        </div>
                        <div class="content">
                            <p class="title-content">2019 - Present</p>
                            <p class="data-content">Universitas Indonesia</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="foto">
                <img class="jp04" src="{% static 'images/JP04-smaller.png' %}"/>
            </div>
        </div>

    </section>

    {% endblock %}
</body>

app_ppw/templates/jadwal_kegiatan.html
{% extends 'base.html' %}
{% load static %}  

<head>
    {% block head %}
    <title>Event List</title>
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="sub-section mb-4">
        <h1><span class="name-title">Event</span> List</h1>
    </div>
    <div class="box-delete-kuliah">
        <div class="box-delete rounded">
            <a href="{% url 'app_ppw:tambah_kegiatan' %}">Add New Event</a>
        </div>
    </div>
    {% for kegiatan in list_kegiatan %}
    <div class="box">
        <div class="box-kuliah">
            <p class="form-content">{{ kegiatan.nama_Kegiatan }}</p>
            {% for member in kegiatan.peserta_set.all %}
            <p class="form-deskripsi deskripsi">{{ member.nama_Peserta }}</p>
            {% endfor %}
        </div>
        <div class="box-delete-kuliah">
            <div class="box-delete rounded">
                <a href="{% url 'app_ppw:tambah_peserta' kegiatan.id %}">Add Event Member</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}
</body>

app_ppw/templates/jadwal_kuliah.html
{% extends 'base.html' %}
{% load static %}   
<head>
    {% block head %}
    <title>Add Course</title>
    {% endblock %}

</head>
<body>
    {% block body %}
    <div class="sub-section mb-5">
        <h1><span class="name-title">Add</span> Course</h1>
    </div>
    <form action="add_kuliah" method="POST" class="add_kuliah">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="submit rounded"/>
    </form>
    {% endblock %}
</body>

app_ppw/templates/list_kuliah.html
{% extends 'base.html' %}
{% load static %}  

<head>
    {% block head %}
    <title>Course List</title>
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="sub-section mb-4">
        <h1><span class="name-title">Course</span> List</h1>
    </div>
    <div class="add-course-button">
        <a href="{% url 'app_ppw:add_kuliah'%}"> Add Course </a>
    </div>
    {% for kuliah in mata_kuliah %}
    <div class="box">
        <div class="box-kuliah">
            <p class="form-content"><a href="{% url 'app_ppw:detail_kuliah' kuliah.id %}" > {{ kuliah.nama_Mata_Kuliah }} </a> </p>
            <p class="form-deskripsi deskripsi"> {{ kuliah.deskripsi }} </p>
        </div>
        <div class="box-delete-kuliah">
            <div class="box-delete rounded">
                <a href="{% url 'app_ppw:delete_kuliah' kuliah.id %}">Delete</a>
            </div>
        </div>
    </div>
    {% endfor %}

    {% endblock %}
</body>

app_ppw/templates/story1.html
{% extends 'base.html' %}
{% load static %}

<head>
    {% block head %}
    <title>Personal Website</title>
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="foto">
        <img class="jp04" src="{% static 'images/JP04-smaller.png' %}"/>
    </div>
    <section class="mt-4">
        <div class="desc">
            <h2>DESKRIPSI</h2>
            <p class="data-content">Mahasiswi Fakultas Ilmu Komputer, Universitas Indonesia. Senang mempelajari hal baru terutama yang berkaitan dengan web development. Saya senang membaca, menggambar, dan menonton anime :D</p>
        </div>
        <div class="biodata">
            <h2>BIODATA</h2>
            <div class="cont">
                <p class="data">Nama Lengkap : Alisha Yumna Bakri</p>
                <p class="data">Nama Penggilan : Alisha</p>
                <p class="data">NPM : 1906400173</p>
                <p class="data">Angkatan : 2019</p>
                <p class="data">Tempat Kuliah : Universitas Indonesia</p>
                <p class="data">Hobi: Menggambar, membaca novel, dan menonton anime</p>
            </div>
        </div>

        <div class="riwayat">
            <h2>RIWAYAT PENDIDIKAN</h2>
            <div class="cont">
                <p class="data">2009 - 2013 : SD Semut-Semut</p>
                <p class="data">2013 - 2016 : SMPIT Nurul Fikri</p>
                <p class="data">2016 - 2019 : SMAN 26 Jakarta</p>
                <p class="data">2019 - Sekarang : Universitas Indonesia</p>
            </div>
        </div>

    </section>

    {% endblock %}
</body>

app_ppw/templates/tambah_kegiatan.html
{% extends 'base.html' %}
{% load static %}   
<head>
    {% block head %}
    <title>Add Event</title>
    {% endblock %}

</head>
<body>
    {% block body %}
    <div class="sub-section mb-5">
        <h1><span class="name-title">Add</span> Event</h1>
    </div>
    <form action="{% url 'app_ppw:tambah_kegiatan' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="submit rounded"/>
    </form>
    {% endblock %}
</body>

app_ppw/templates/tambah_peserta.html
{% extends 'base.html' %}
{% load static %}   
<head>
    {% block head %}
    <title>Add Event</title>
    {% endblock %}

</head>
<body>
    {% block body %}
    <div class="sub-section mb-5">
        <h1><span class="name-title">Add</span> Event </h1>
    </div>
    <form action="{% url 'app_ppw:tambah_peserta' id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="submit rounded"/>
    </form>
    {% endblock %}
</body>